[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "pnpm i --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node dist/index.js"
